### ISSUE TITLE
CoT version of MathV360K

### ISSUE THREAD

**Issue by lockon-n** [HZQ950419/Math-LLaVA#3]
Thanks for sharing this nice work!

I'm wondering if there is a CoT version of MathV360K, seems currently the dataset only contains the final answer without the intermediate rationale.

**Comment by lockon-n** [comment]
By the way, is it convenient to provide the split of the 40K original data as well as the 320K augmented data?

**Comment by steven640pixel** [comment]
Hi,
We have tried the CoT version of MathV360K, and the performance dropped in comparison. Possible reasons are that the quality of the generated intermediate steps are not good enough, and that the CoT increases the difficulty of learning.
And we will release the split of 40K original data soon.

**Comment by lockon-n** [comment]
Thanks for the reply! That's really helpful!

**Comment by lockon-n** [comment]
> CoT version of MathV360K

By the way, seems you have generated "CoT version of MathV360K", is there any plan to release it?

**Comment by steven640pixel** [comment]
Hi,
The ids of 40K original data are from identity_0 to identity_38733.
And generated CoT version can be downloaded from ["here"](https://drive.google.com/file/d/1VfObd3MPQw_afAb83gj1h21qEUGAK75s/view?usp=drive_link).

**Comment by lockon-n** [comment]
You guys are so nice! Thanks for all the efforts you have made! :))

**Comment by YerongLi** [comment]
> Hi, The ids of 40K original data are from identity_0 to identity_38733. And generated CoT version can be downloaded from ["here"](https://drive.google.com/file/d/1VfObd3MPQw_afAb83gj1h21qEUGAK75s/view?usp=drive_link).

How did you generate the CoT version of the training set?
